services:

  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  chatbot:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
    restart: unless-stopped
